# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-19 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20191119_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
