# Generated by Django 3.2.6 on 2021-08-20 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_featureditem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='content',
            new_name='description',
        ),
    ]
